# SPDX-FileCopyrightText: 2026 Jean-Pierre De Jesus DIAZ <me@jeandudey.tech>
# SPDX-License-Identifier: Apache-2.0 OR MIT

load("//common:defs.bzl", "filegroup_strip_prefix")

# The Guile modules MesCC parses C with. Mes carries two NYACC files itself and
# expects the rest on the load path.
filegroup_strip_prefix(
    name = "modules",
    srcs = glob(["src/module/**"]),
    prefix = "src/module/",
    visibility = ["PUBLIC"],
)
